# ===============================
# MPI / execution settings
# ===============================
mpi:
  use_mpi: true

# ===============================
# Run control
# ===============================
run:
  restart_run: false
  newdir_name: "stacks_apr17/"
  test: false
  nObj_test: 1000   # only used if test=true

# ===============================
# Error estimation
# ===============================
errors:
  enabled: true
  nreg: 4   # number of regions if enabled

# ===============================
# Stacking / analysis options
# ===============================
analysis:
  orient: "asym_xy"   # options: original, random, sym, asym_x, asym_y, asym_xy
  cutout_rad_mpc: 20.0
  dz_rescale: 0.01
  zmin:  # define if you want to limit the redshift range smaller than that in the catalog
  zmax: 

# ===============================
# Paths
# ===============================
paths:
  # basepath: "/mnt/scratch-lustre/mlokken/stacking/ACTxDESI/orient_by_desi_lrgc_100/stacks/enmap/"
  basepath: "/mnt/scratch-lustre/mlokken/stacking/ACTxDESI/dr1_lrg_allpython/"
  orient_file: "/mnt/scratch-lustre/mlokken/stacking/ACTxDESI/dr1_lrg_allpython/desi_dr1_lrgc_10pt0Mpc_cuts_asym_xy.csv"

# ===============================
# Maps to stack
# ===============================
maps:
  map1:
    type: "y"
    path: "/mnt/raid-cita/mlokken/data/act_ymaps/ilc_SZ_yy.fits"
    shortname: "ACT_y_fid"

