# ===============================
# MPI / execution settings
# ===============================
mpi:
  use_mpi: false

# ===============================
# Run control
# ===============================
run:
  save_path: "/mnt/scratch-lustre/mlokken/stacking/flamingo/dr1_lrg_allpython/"
  write_maps_to_file: True
  filenames_in_Mpc: True

# ===============================
# Input files
# ===============================
files:
  stacking_object_catalog: "/mnt/raid-cita/mlokken/data/flamingo/siegelcut_LRG_logmstar11.20_combined_z0.85-1.15_L1000N1800_HYDRO_FIDUCIAL_lc.npz" 
  orient_object_catalog: "/mnt/raid-cita/mlokken/data/flamingo/siegelcut_LRG_logmstar11.20_combined_z0.85-1.15_L1000N1800_HYDRO_FIDUCIAL_lc.npz"
  randoms_catalog:
  mask: "/mnt/raid-cita/mlokken/data/flamingo/mask_dec_-30_15_1024.fits"

# ===============================
# Stacking / analysis options
# ===============================
analysis:
  # define the width in comoving Mpc for stacking object bins
  stacking_slice_width_Mpc: 5
  # and for orientation object bins
  orientation_slice_width_Mpc: 40
  nu_min: 
  nu_max: 
  e_min: 
  e_max: 
  los_split_mode: 'auto_overlap'
  fraction_input_data: 1
  smoothing_Mpc: 10
  orientation_mode: 'asym_xy'
  center_objects_label: 'lrg11p2'
  orient_objects_label: 'lrg11p2'
  healpix_nside: 1024
  z_min: 0.9
  z_max: 0.93
