# ===============================
# MPI / execution settings
# ===============================
mpi:
  use_mpi: true

# ===============================
# Run control
# ===============================
run:
  restart_run: false
  newdir_name: "actdesi_lrgs_p7_p9_20reg_teststack/"
  test: true
  nObj_test: 1000   # only used if test=true

# ===============================
# Error estimation
# ===============================
errors:
  enabled: true
  nreg: 20   # number of regions if enabled

# ===============================
# Input catalog constraints
# ===============================
catalog:
  constraint_str: "lrgc_nocut_lrgc_nocut_noorient_100pct_0.7_0.9"

# ===============================
# Stacking / analysis options
# ===============================
analysis:
  orient: "original" # "asym_xy"   # options: original, random, sym, asym_x, asym_y, asym_xy
  cutout_rad_mpc: 20.0
  dz_rescale: 0.01
  zmin: 0.7 # define if you want to limit the redshift range smaller than that in the catalog
  zmax: 0.9

# ===============================
# Paths
# ===============================
paths:
  basepath: "/pscratch/sd/r/rhlozek/stacking/ACTxDESI/orient_by_desi_lrgc_100/stacks/enmap/"
  stack_pts_path: "/pscratch/sd/r/rhlozek/stacking/data/desi/stacking_points/"

# ===============================
# Maps to stack
# ===============================
maps:
  map1:
    type: "y"
    path: "/global/cfs/projectdirs/act/www/dr6_nilc/ymaps_20230220/ilc_actplanck_ymap.fits"
    shortname: "ACT_y_fid"

