# ===============================
# MPI / execution settings
# ===============================
mpi:
  use_mpi: false

# ===============================
# Run control
# ===============================
run:
  save_path: "/mnt/scratch-lustre/mlokken/stacking/ACTxDESI/dr1_lrg_allpython/"
  write_maps_to_file: false
  filenames_in_Mpc: True

# ===============================
# Input files
# ===============================
files:
  stacking_object_catalog: "/mnt/raid-cita/mlokken/data/desi/LRG_clustering_Y1_zred_desi_complete_thresh0.7_excl0.4deg_ACTmasked.fits" # double-masked version
  orient_object_catalog: "/mnt/raid-cita/mlokken/data/desi/LRG_clustering_ML.dat.fits"
  randoms_catalog: "/mnt/raid-cita/mlokken/data/desi/randoms/LRG_comb11_clustering.ran.fits"

# ===============================
# Stacking / analysis options
# ===============================
analysis:
  nu_min: 2
  nu_max: 
  e_min: 0.3
  e_max: 
  los_split_mode: 'auto_overlap'
  fraction_input_data: 1
  smoothing_Mpc: 10
  orientation_mode: 'asym_xy'
  center_objects_label: 'desi_dr1_lrgc'
  orient_objects_label: 'desi_dr1_lrgc'
  healpix_nside: 1024
  z_min: 0.6
  z_max: 0.65